### ISSUE TITLE
npm install also decides to install bower

### ISSUE THREAD

**Issue by janat08** [corejavascript/typeahead.js#96] opened 2016-11-14 13:31 UTC
meteor npm install corejs-typeahead

> corejs-typeahead@0.11.1 postinstall /home/jk/Documents/garlic/node_modules/corejs-typeahead
> bower install

sh: 1: bower: not found
npm ERR! Linux 4.8.0-27-generic
npm ERR! argv "/home/jk/.meteor/packages/meteor-tool/.1.4.2_1.1a69i4q++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/jk/.meteor/packages/meteor-tool/.1.4.2_1.1a69i4q++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install" "corejs-typeahead"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! corejs-typeahead@0.11.1 postinstall: `bower install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the corejs-typeahead@0.11.1 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the corejs-typeahead package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs corejs-typeahead
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls corejs-typeahead
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jk/Documents/garlic/npm-debug.log

**Comment by svbergerem** [comment] 2016-11-14 14:10
Sounds like a duplicate of #47.

**Comment by jlbooker** [comment] 2016-11-14 15:11
@janat08 Yes, this is a duplicate and is fixed in our beta release. Try: `meteor npm install corejs-typeahead@beta`. This release (v1.0.0) should be out soon as the default version to install (i.e. without the "@beta" tag).

The other workaround is to just globally install bower first. (`npm install -g bower`)

**Closed by jlbooker** 2016-11-14 15:11 UTC
