### ISSUE TITLE
Limit does not work

### ISSUE THREAD

**Issue by tqdo** [corejavascript/typeahead.js#233] opened 2020-11-09 01:41 UTC
I don't really know why limit does not seem to work. Below is my code. I want to set limit to 15 but it always show 5 suggestions maximum. Really appreciate any healp

````
var suggestionName = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.obj.nonword('name'),
            queryTokenizer: Bloodhound.tokenizers.nonword,
            local: data,
            items: 15,
            limit: 15,
        });
        suggestionName.initialize()

let searchMaster = $('#searchBoxMaster')
        searchMaster.typeahead({
                hint: false,
                highlight: true,
                minLength: 1,
            },
            {
                name: 'Indicators',
                source: suggestionName,
                items: 15,
                limit: 15,
                displayKey: 'value',
            });
````

**Comment by jlbooker** [comment] 2020-11-09 16:08
A couple things I've noticed...

The `limit` parameter should be passed in the typeahead dataset, not in the Bloodhound parameters, so you can remove that.

I'm not sure what the `items` parameter you've included in both places. That doesn't appear anywhere in the docs.

Also, verify that more than five suggestions are being returned in the dataset. You should be able to call `suggestionName.search(...)` directly to see the results from the Bloodhound instance. See the [docs on the .search() method](https://github.com/corejavascript/typeahead.js/blob/master/doc/bloodhound.md#bloodhoundsearchquery-sync-async).

If the problem persists, I'd suggest creating a JSFiddle of CodePen example to reproduce it.

**Comment by FluffyDiscord** [comment] 2021-01-12 13:12
Adding `limit` at `typeahead` somehow makes it that nothing shows, even when data is supplied.

```javascript
this.input.typeahead(null, {
    name: 'response',
    display: '_none',
    source: this.bloodhound,
    limit: 10,
    templates: {
        suggestion: (response) => {
            if(response['type'] === 'product') {
                return this._getProduct(response);
            }
        }
    }
});
```

**Comment by jlbooker** [comment] 2021-01-12 19:25
@FluffyDiscord Could you create a minimum reproducible test case in JSFiddle or CodePen using the latest release of Typeahead.js?

**Comment by FluffyDiscord** [comment] 2021-01-12 20:06
Why are you closing it, it does not work for me, I will try to include snippet I use. Nver used JSFiddle before

**Closed** 2021-01-12 20:05 UTC

**Comment by jlbooker** [comment] 2021-01-14 17:00
Hi @FluffyDiscord, Perhaps @tqdo closed this because it started as a pretty specific question about the code in the original post. Happy to have you start a new issue with your test case in a JsFiddle or CodePen so we can reproduce it.

**Comment by sokollondon** [comment] 2021-05-14 12:01
Same problem! Always show 5 suggestions

```js
$('#typeahead').typeahead({
    limit: 10,
    minLength: 0
},{
    source: function(q, cb){cb(['1','2','3','4','5','6','7','8','9','10'])}
});
```

[v1.3.1](https://github.com/corejavascript/typeahead.js/blob/master/dist/typeahead.jquery.js)
