### ISSUE TITLE
NPM and Bower releases

### ISSUE THREAD

**Issue by CoreSystemDevelopment** [corejavascript/typeahead.js#9] opened 2015-10-04 09:26 UTC
From #3 

I don't really know how we should handle this. **'typeahead.js'** is currently registered for the abandoned twitter repository's. @rwjblue said in his **[comment](https://github.com/bower/bower/issues/120#issuecomment-34131083)**:

> As mentioned above, we are not to remove/change any repos registered to Twitter.

So perhaps we should use **'typeahead'** instead of **'typeahead.js'**?

/cc @corejavascript/collaborators

**Comment by rosskevin** [comment] 2015-10-16 17:29
I'm attempting to pull using `"typeahead.js": "git@github.com:corejavascript/typeahead.js.git"` in my bower.json, but only get readme updates, for some reason it doesn't pull master.  What am I missing there?

It appears that `typeahead` is available, so that's my vote for package name.

**Comment by jcrben** [comment] 2015-10-16 18:21
I actually think name spacing to corejavascript-typeaheadjs might be more clear. 'typeahead' is super-generic and often associated with bootstrap typeahead. 

If this project is successful, I hope to bring other abandoned projects under this umbrella. For example, gridster is abandoned but has a semi-active fork or two.

**Comment by jcrben** [comment] 2015-10-16 18:23
I meant is namespacing could help build awareness of the 'corejavascript' brand.

**Comment by rosskevin** [comment] 2015-10-16 18:37
Sounds good, but I've always been perplexed at the `js` extension from a project branding perspective.  Does it add value other than the fact that the legacy name has it?  I'd recommend `corejavascript-typeahead`.

**Comment by jcrben** [comment] 2015-10-16 18:48
My guess is that `typeaheadjs` was selected because `typeahead` was overloaded by its association with Bootstrap typeahead. There are libraries that respond differently based on these names I think, such as bootstrap-tagsinput. And since this project is derived from typeaheadjs, I think it'd probably add to confusion to remove it...

**Comment by ApfelUser** [comment] 2015-10-16 20:06
We also could to either

 * **corejs-typeahead** and
 * **corejs-typeaheadjs**

Because `corejavascript` is so annoyingly long. I just took that for the URL because `corejs` wasn't available anymore. I am not sure about the **js** thing. I really would like it as short as possible, and I don't think that there is much more confusion as we're changing the name anyway. I actually also really like just **typeahead**. Man. This is hard. :smile:

What do you think @CoreSystemDevelopment & @jesperronn?

And @jcrben - yep, that is what this organization was intended to. Bringing abandoned projects back to life :+1:

**Comment by jcrben** [comment] 2015-10-16 21:14
corejs-typeahead seems sufficiently distinct, doesn't bother me.

**Comment by duzun** [comment] 2015-10-21 10:40
corejs-typeahead +1

**Comment by fkammer** [comment] 2015-10-21 14:11
corejs-typeahead +1

**Comment by jesperronn** [comment] 2015-10-21 14:14
:+1: for corejs-typeahead 

(we need to put in that it's a fork of deprecated twitter-typeahead-js first in the README)

**Comment by Lapeth** [comment] 2015-10-28 18:11
corejs-typeahead +1
We need this in the NPM.

**Comment by ApfelUser** [comment] 2015-10-28 18:39
@Lapeth We're waiting for these:
**[milestones/v0.11.2](https://github.com/corejavascript/typeahead.js/milestones/v0.11.2)**
to be merged and/or fixed, then we'll push our first release to bower and npm :smiley:

**Comment by jcrben** [comment] 2015-11-15 08:31
I noticed just now that there's a pretty popular 'core-js' library: https://github.com/zloirock/core-js - so this project introduced another potential naming weirdness into the javascript ecosystem.

**Comment by mwjackson** [comment] 2016-01-19 14:55
+1 for communityjs

**Comment by jlbooker** [comment] 2016-11-17 14:55
V 1.0.1 has been released!! Hurrah! https://www.npmjs.com/package/corejs-typeahead

**Closed by jlbooker** 2016-11-17 14:55 UTC
Labels: enhancement, help wanted, question
