### ISSUE TITLE
typeahead:select event does not pass dataset name

### ISSUE THREAD

**Issue by onokazu** [corejavascript/typeahead.js#89] opened 2016-09-08 19:19 UTC
The typeahead:selected event, when triggered, used to pass the name of the dataset of the item selected as the third parameter, but it doesn't anymore for the typeahead:select event. How do we know the name of the dataset the selected item belongs to?

**Comment by jlbooker** [comment] 2016-11-07 15:23
@onokazu Is this related (and possibly fixed by) #65?

**Comment by jlbooker** [comment] 2016-11-10 16:10
Duplicate of #63 and #58

**Closed by jlbooker** 2016-11-10 16:10 UTC
Labels: bug, duplicate
