### ISSUE TITLE
typeahead undefined

### ISSUE THREAD

**Issue by bryanrasmussen** [corejavascript/typeahead.js#112] opened 2017-01-08 21:34 UTC
I was switching to corejavascript typeahead because I kept getting this error in the twitter version, but still here

the following code 

var _ = require('underscore');
//TODO remove all the commented out code that was done to check if twitters typeahead was able to work under our architecture.
require('corejs-typeahead');
var substringMatcher = function(strs) {
  return function findMatches(q, cb) {
    var matches, substringRegex;

    // an array that will be populated with substring matches
    matches = [];

    // regex used to determine if a string contains the substring `q`
    substrRegex = new RegExp(q, 'i');

    // iterate through the pool of strings and for any string that
    // contains the substring `q`, add it to the `matches` array
    $.each(strs, function(i, str) {
      if (substrRegex.test(str)) {
        matches.push(str);
      }
    });

    cb(matches);
  };
};

var states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
  'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii',
  'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
  'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
  'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
  'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota',
  'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
  'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
  'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
];
//This is not necessarily the way we will be doing autcompletion in every usage. Here I am instead providing examples that we can use for development.
var stepSetter = function($el) {
  var $steps = $el.find('.autocompletable');
  if ($steps.length > 0) {
    $steps.each(function(item) {
      var $step = $(this);
      console.log(typeof $step.typeahead);
      
      $step.typeahead({
        hint: true,
        highlight: true,
        minLength: 1
      },
      {
        name: 'states',
        source: substringMatcher(states)
      });
    });
  }
};

$(document).ready(function() {
  $('.js-autocompleter').each(function() {
    var $el = $(this);
    var id = $el.attr('id');
    var config = $el.data('config') ? $el.data('config') : null;
    stepSetter($el);
  });
});

finds the input that I want to add typeahead to 
shown in the following html
<div class='js-autocompleter' id='js-singleprefillautocomplete-example'>
  <input class='autocompletable' type='text' data-step='true'>
</div>

unfortunately my console.log statement of typeof $step.typeahead tells me undefined.

**Comment by bryanrasmussen** [comment] 2017-01-08 21:55
I have also tried require('corejs-typeahead/dist/typeahead.bundle.min'); 

corejs-typeahead is found in my node modules, the require statement doesn't have a problem. An absolute path to the library has the same result, so it is evidently not that the library is not being loaded.

**Comment by jlbooker** [comment] 2017-01-09 16:55
The code examples you gave are hard to read because of the formatting, but it looks like you have a lot of extra code that's not needed or could be interfering with Typeahead.

Try removing as much code as you can, down to just the Typeahead component. Please try to reproduce the problem using a site like https://jsfiddle.net/, so we can see and run your code better.

**Comment by bryanrasmussen** [comment] 2017-01-09 21:12
It seems to be a browserify related issue, I've replicated the example at https://gist.githubusercontent.com/jharding/9458744/raw/94c98ffbb7496ce16ac8067dd5b2867182ea4c04/the-basics.js 
in my browserify build except that my difference is that I use 
require('corejs-typeahead'); 
before the example to include typeahead. 

From what I've read from people having similar issues with twitter's version of the library it is because I've included a JQuery instance before, and typeahead bundles its own?

**Comment by bryanrasmussen** [comment] 2017-01-09 21:32
never mind, looks like it was caching on my end. Now it works.

**Comment by bryanrasmussen** [comment] 2017-01-09 22:13
Ok going to have to reopen, and I guess it is this browserify problem I've been reading about (can't find the exact issues thread I was reading) - the above code worked but as soon as I wrapped it in a document ready I got typeahead is not a function. so the following

```
require('corejs-typeahead');

var substringMatcher = function(strs) {
  return function findMatches(q, cb) {
    var matches, substringRegex, substrRegex;

    // an array that will be populated with substring matches
    matches = [];

    // regex used to determine if a string contains the substring `q`
    substrRegex = new RegExp(q, 'i');

    // iterate through the pool of strings and for any string that
    // contains the substring `q`, add it to the `matches` array
    $.each(strs, function(i, str) {
      if (substrRegex.test(str)) {
        matches.push(str);
      }
    });

    cb(matches);
  };
};

var states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
  'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii',
  'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
  'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
  'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
  'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota',
  'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
  'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
  'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
];

$(document).ready(function() {
  console.log('doc ready runs but no typeahead');
  $('#the-basics .typeahead').typeahead({
      hint: true,
      highlight: true,
      minLength: 1
    },
    {
      name: 'states',
      source: substringMatcher(states)
    }
  );
});
```

gives me a console.log statement saying doc ready runs but no typeahead, followed by TypeError: $(...).typeahead is not a function. This is in Firefox developer and Chrome.

**Comment by jlbooker** [comment] 2017-01-11 02:49
Try running `console.log($('#the-basics .typeahead'))`, just to be sure you have a valid jQuery object to call `.typeahead()` on. If that doesn't turn up anything, then my guess is that the problem has to do with browserify and how it's loading jQuery and/or typeahead. It sounds like either typeahead is not getting included, or that you're re-including jQuery somewhere further down the page (which resets jQuery).

**Comment by bryanrasmussen** [comment] 2017-01-11 07:51
I think you're probably going to turn out right that it is something to do
with how browserify loads jquery in our build. However I expect that
browserify is loading typeahead fine because it works as long as I don't
put the $(document).ready around it, and the document ready event is
running.

I was thinking the solution might be found in porting this
https://github.com/nikvdp/typeahead.js-browserify to use corejs typeahead -
it's very minimal.

But I will try to see if I can play with the import order first.


Thanks

**Comment by jlbooker** [comment] 2017-01-11 14:46
@bryanrasmussen Yea, I think this confirms it for me.. The tell-tell sign to me is that Typeahead *is* defined if it's executed as the browser parses the JS, but then is no longer defined by the time the `$(document).ready` handler executes. Something is being included in the JS after Typeahead (but it runs before `onReady`) that's clearing the reference to `.typeahead()`. I'm guessing that's because jQuery is being included a second time.

I'll close this for now, but feel free to reopen if you discover more.

**Closed by jlbooker** 2017-01-11 14:46 UTC

**Comment by PikachuEXE** [comment] 2017-10-10 02:09
@bryanrasmussen @jlbooker 
If you are free please take a look at #164.
It might solve this issue.
